"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class control_t(object):
    __slots__ = ["timestamp", "motor", "servo"]

    __typenames__ = ["int64_t", "float", "float"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.timestamp = 0
        self.motor = 0.0
        self.servo = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(control_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qff", self.timestamp, self.motor, self.servo))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != control_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return control_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = control_t()
        self.timestamp, self.motor, self.servo = struct.unpack(">qff", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if control_t in parents: return 0
        tmphash = (0xcc5c654bac572c0d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if control_t._packed_fingerprint is None:
            control_t._packed_fingerprint = struct.pack(">Q", control_t._get_hash_recursive([]))
        return control_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

