"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class control_motor_t(object):
    __slots__ = ["timestamp", "motor"]

    __typenames__ = ["int64_t", "float"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.timestamp = 0
        self.motor = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(control_motor_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qf", self.timestamp, self.motor))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != control_motor_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return control_motor_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = control_motor_t()
        self.timestamp, self.motor = struct.unpack(">qf", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if control_motor_t in parents: return 0
        tmphash = (0xcf7fd06741aed480) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if control_motor_t._packed_fingerprint is None:
            control_motor_t._packed_fingerprint = struct.pack(">Q", control_motor_t._get_hash_recursive([]))
        return control_motor_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

