"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class imu_fusion_t(object):
    __slots__ = ["timestamp", "pitch", "roll", "yaw"]

    __typenames__ = ["int64_t", "float", "float", "float"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        self.pitch = 0.0
        self.roll = 0.0
        self.yaw = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(imu_fusion_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qfff", self.timestamp, self.pitch, self.roll, self.yaw))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != imu_fusion_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return imu_fusion_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = imu_fusion_t()
        self.timestamp, self.pitch, self.roll, self.yaw = struct.unpack(">qfff", buf.read(20))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if imu_fusion_t in parents: return 0
        tmphash = (0xaeff12c009495049) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if imu_fusion_t._packed_fingerprint is None:
            imu_fusion_t._packed_fingerprint = struct.pack(">Q", imu_fusion_t._get_hash_recursive([]))
        return imu_fusion_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

